# Use the official Elasticsearch Docker image as the base image
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.0

# Expose ports
EXPOSE 9200
EXPOSE 9300

# Set environment variables
ENV discovery.type=single-node
